### ISSUE TITLE
Support ESLint 8

### ISSUE THREAD

**Issue by gabrielmdeal** [amanda-mitchell/suppress-eslint-errors#173]
When I try to run `suppress-eslint-errors`, I get this error:

>  ERR src/app/graphQlClient/index.ts Transformation error (CLIEngine is not a constructor)
TypeError: CLIEngine is not a constructor
    at codeMod (/home/gabrielx/projects/oss/oss_ms_teams/node_modules/suppress-eslint-errors/transforms/suppress-eslint-errors.js:12:23)

My project uses ESLint and I see that `CLIEngine` has been removed in ESLint 8: https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#the-cliengine-class-has-been-removed

**Comment by Endran** [comment]
As a workaround, I was able to temporarily just revert from `eslint": "^8.8.0`, to `eslint": "^7.32.0`. Then I could run `suppress-eslint-errors`, and immediately switch back to the latest eslint.

**Comment by erikmellum** [comment]
This also caught me up, but was able to use the recommended 7.32.0. @mizdra I would love to try yours out sometime as well. I like the interactive idea a lot!

**Comment by amanda-mitchell** [comment]
Fixed in 3.0.1
