### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by NMinhNguyen** [amanda-mitchell/suppress-eslint-errors#219]
Hi @amanda-mitchell, would you please be able to publish a new version to npm? The one currently published [depends on `jscodeshift@0.11.0`](https://unpkg.com/suppress-eslint-errors@2.0.4/package.json) which has a missing dependency on `lodash`. This issue has been fixed in 0.13.0: https://github.com/facebook/jscodeshift/pull/455#issuecomment-1038388944. Dependabot has already taken care of bumping dependency versions in the repo so I don't think you'd need to do much besides just publishing a new version.

**Comment by amanda-mitchell** [comment]
Done.
