### ISSUE TITLE
Do not add an additional comment by default

### ISSUE THREAD

**Issue by mracette** [amanda-mitchell/suppress-eslint-errors#221]
For my use case, I would like to suppress errors without adding an additional comment. 
It doesn't seem like this is currently possible, because a [default comment is added when none is specified](https://github.com/amanda-mitchell/suppress-eslint-errors/blob/main/transforms/suppress-eslint-errors.js#L31).
IMO, the default behavior should be _not_ to add an additional comment. But at a minimum, I think the behavior should be changed so that there is an _option_ to not add a comment.

**Comment by amanda-mitchell** [comment]
I feel very strongly that suppressing eslint errors without proper documentation is an anti-pattern, and I will not make this the default.

However, I would be willing to review a PR that adds an option for this.
