### ISSUE TITLE
How to run suppress-eslint-errors with Typescript

### ISSUE THREAD

**Issue by JasonMore** [amanda-mitchell/suppress-eslint-errors#29]
It took me a while to track down how to use this with Typescript. Could you update the readme? Or leave this issue open

```
npx suppress-eslint-errors --parser=tsx --extensions=tsx,ts,jsx,js  src
```

**Comment by JasonMore** [comment]
@amanda-mitchell any thoughts on this?

**Comment by amanda-mitchell** [comment]
I’d be happy to entertain a PR!
