### ISSUE TITLE
Can't find files - "No files selected, nothing to do."

### ISSUE THREAD

**Issue by dangerismycat** [amanda-mitchell/suppress-eslint-errors#7]
Using the command
```
npx suppress-eslint-errors ./app --rules=no-unused-vars --message="Please fix this the next time the file is edited." --extensions=js
```
I continue to get the message "No files selected, nothing to do.". What am I missing?

**Comment by amanda-mitchell** [comment]
The first thing that I'd recommend checking is whether you have any exclusions (lines that start with `!`) in your `.gitignore`.

`jscodeshift` currently has a bug that will cause *all* files to be ignored when these are present. 😞

A new version of `suppress-eslint-errors` will be published soon that will skip the inclusion of the `.gitignore` file when it contains these, and I hope to contribute an upstream fix to `jscodeshift` in the near future. As a workaround in the meantime, try commenting out these lines in your `.gitignore`, if you have them.

(also: sorry for the long delay! The project was left without a maintainer after I left my former employer, but I recently re-adopted it)

**Comment by amanda-mitchell** [comment]
@dangerismycat, could you try running the latest version to see if you still encounter this behavior? (`npx` should always pull down the latest)

**Comment by amanda-mitchell** [comment]
Closing from lack of activity.
